### ISSUE TITLE
If there is no changelog packing fails

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#16]
If there is no Changes file packing fails with:
```
[   33s] + node2rpm-server --prep
[   33s] /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/changelog.rb:23:in `entries_suse': undefined method `map!' for nil:NilClass (NoMethodError)
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/changelog.rb:13:in `entries'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/parser.rb:29:in `parse'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:32:in `buildroot'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:27:in `buildroot'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:9:in `initialize'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `new'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `<top (required)>'
[   33s] 	from /usr/bin/node2rpm-server:23:in `load'
[   33s] 	from /usr/bin/node2rpm-server:23:in `<main>'
[   33s] error: Bad exit status from /var/tmp/rpm-tmp.iwSYtn (%prep)
```

**Comment by marguerite** [comment]
@illuusio can you paste your project...I need to see how "no changelog" looks like. I handled the case for an empty "%changelog" in specfile. I need to see if it fails, or something like no "%changelog" at all, or a "%changelog\n\n\n\n" case

**Comment by illuusio** [comment]
Actually adding .changes file fixed this so if there is no changelog or no .changes file it fails. Template came from node2rpm package.

**Comment by marguerite** [comment]
looks like it has been fixed
