### ISSUE TITLE
Can't build uglifyjs anymore

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#18]
Building Uglifyjs doesn't work anymore after whiching to upstream nodejs-packaging. It produces error:
```
[   48s] + node2rpm-server --prep
[   49s] /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/changelog.rb:24:in `entries_suse': undefined method `map!' for nil:NilClass (NoMethodError)
[   49s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/changelog.rb:13:in `entries'
[   49s] 	from /usr/lib64/ruby/gems/2.1.0/gems/rpmspec-1.0.0/lib/rpmspec/parser.rb:29:in `parse'
[   49s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:32:in `buildroot'
[   49s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/system.rb:27:in `buildroot'
[   49s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:10:in `initialize'
[   49s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `new'
[   49s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:7:in `<top (required)>'
[   49s] 	from /usr/bin/node2rpm-server:23:in `load'
[   49s] 	from /usr/bin/node2rpm-server:23:in `<main>'
[   49s] error: Bad exit status from /var/tmp/rpm-tmp.uUCDaw (%prep)
```
Package can be found here: https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/uglifyjs

**Comment by marguerite** [comment]
please remove :uglifyjs under %changelog and write changlog in.changes file

**Comment by illuusio** [comment]
Ok you should have .changes and have something in it (if not it won't build).. It could be nice to check if changes size is 0 so it won't crash but closing.
