### ISSUE TITLE
Broken tars inside packages

### ISSUE THREAD

**Issue by illuusio** [marguerite/nodejs-packaging#21]
It seems there is broken tars inside nodejs 'tar' which makes packaging script fall error like this:

```
[   37s] Untaring /home/abuild/rpmbuild/SOURCES/tar-2.2.1.tgz
[   37s] Renaming /home/abuild/rpmbuild/SOURCES/package to /home/abuild/rpmbuild/SOURCES/tar-2.2.1
[   37s] Untaring /home/abuild/rpmbuild/SOURCES/tar-2.2.1/test/fixtures.tgz
[   37s] Untaring /home/abuild/rpmbuild/SOURCES/tar-2.2.1/test/cb-never-called-1.0.1.tgz
[   37s] 
[   37s] gzip: stdin: unexpected end of file
[   37s] tar: Unexpected EOF in archive
[   37s] tar: Unexpected EOF in archive
[   37s] tar: Error is not recoverable: exiting now
[   37s] Renaming /home/abuild/rpmbuild/SOURCES/tar-2.2.1/test/package to /home/abuild/rpmbuild/SOURCES/tar-2.2.1/test/cb-never-called-1.0.1
[   37s] Untaring /home/abuild/rpmbuild/SOURCES/tar-2.2.1/test/fixtures.tgz
[   37s] /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:124:in `basename': no implicit conversion of nil into String (TypeError)
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:124:in `unpack'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:104:in `block in recursive_untar'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:99:in `glob'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:99:in `recursive_untar'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:111:in `block (2 levels) in recursive_untar'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:111:in `each'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:111:in `block in recursive_untar'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:99:in `glob'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:99:in `recursive_untar'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:24:in `prep'
[   37s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:11:in `<top (required)>'
[   37s] 	from /usr/bin/node2rpm-server:23:in `load'
[   37s] 	from /usr/bin/node2rpm-server:23:in `<main>'
[   37s] error: Bad exit status from /var/tmp/rpm-tmp.augKU5 (%prep)
[   37s] 
[   37s] 
[   37s] RPM build errors:
[   37s]     Bad exit status from /var/tmp/rpm-tmp.augKU5 (%prep)
[   37s] 
[   37s] lamb51 failed "build postcss-cli.spec" at Wed Sep  6 13:19:52 UTC 2017.
```
As it's correct behavior to crash it should be probably be done more nicely with testing is tar archive correct or not try to untar from test-directories as they are not needed.

Package can be found here: https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/postcss-cli

**Comment by marguerite** [comment]
@illuusio I think the only thing I can do is to skip test directories...testing if the tar archive is correct is wrong, because it should crash if packager uploaded wrong source or correct source with wrong suffix.

the 'skip' can only skip directory exactly named "\/(test|tests|testing)\/", because some nodejs module may call itself 'unittest', that is, I need to maintain another regex :-(

**Comment by illuusio** [comment]
Yes I can't see better option. It's not 'perfect' but works most of the time.

**Comment by marguerite** [comment]
Fixed
